### ISSUE TITLE
Cannot crete vectorized feature

### ISSUE THREAD

**Issue by silversurfer147** [endgameinc/ember#20]
Hi, I have a problem with function create_vectorized_feature. If I run it, I always get error message 

```
ember.create_vectorized_features("/ember_dataset/ember/")
Vectorizing training set
Traceback (most recent call last):

  File "<ipython-input-3-38013b95de24>", line 1, in <module>
    ember.create_vectorized_features("/ember_dataset/ember/")

  File "C:\Users\Michal\Anaconda3\lib\site-packages\ember-0.1.0-py3.6.egg\ember\__init__.py", line 71, in create_vectorized_features
    vectorize_subset(X_path, y_path, raw_feature_paths, 900000)

  File "C:\Users\Michal\Anaconda3\lib\site-packages\ember-0.1.0-py3.6.egg\ember\__init__.py", line 51, in vectorize_subset
    X = np.memmap(X_path, dtype=np.float32, mode="w+", shape=(nrows, extractor.dim))

  File "C:\Users\Michal\Anaconda3\lib\site-packages\numpy\core\memmap.py", line 221, in __new__
    fid = open(filename, (mode == 'c' and 'r' or mode)+'b')

FileNotFoundError: [Errno 2] No such file or directory: '/ember_dataset/ember/X_train.dat'
```

I am using windows 10, and the path is correct, python file I have in folder D:\Downloads, and dataset are in folder D:\Downloads\ember_dataset\ember, this is my code

```
import ember
ember.create_vectorized_features("/ember_dataset/ember/")
```

Could someone help me? Thank you in advance.

**Comment by varshinichowdary27** [comment]
I am getting the same issue how did you solve it @silversurfer147

**Comment by silversurfer147** [comment]
@varshinichowdary27 I put there absolute path to ember directory 
`ember.create_vectorized_features("D:\ember_dataset\ember")`
